### ISSUE TITLE
Add tutorial data to zenodo

### ISSUE THREAD

**Issue by Basdorsman** [xpsi-group/xpsi#120]
First document would be synthetic_realization.dat from the modeling tutorial

**Comment by Basdorsman** [comment]
Second would be NICER_realisation.dat and XMM_realisation.dat from the instrument synergy tutorial.

**Comment by Basdorsman** [comment]
NICER_expected_hreadable.dat and new_NICER_expected_hreadable.dat from same tutorial

**Comment by thjsal** [comment]
I think all the needed tutorial data are already in that new Zenodo link, since `NICER_realisation.dat` and `NICER_expected_hreadable.dat ` are exactly the same as the example synthetic realisations I added to the X-PSI github repository (`examples/examples_modeling_tutorial/model_data/`), and now also XMM_realisation is also in the same repository. And the `new_NICER_expected_hreadable.dat` is not needed in advance but it is produced when running the tutorial.
