### ISSUE TITLE
Py3 X-PSI doesn't display likelihood value when `likelihood.check` fails

### ISSUE THREAD

**Issue by DevarshiChoudhury** [xpsi-group/xpsi#219]

**Comment by DevarshiChoudhury** [comment]
Turns out to not display when it passes either, although that doesn't matter I suppose. @serenavinciguerra89 also mentioned expanding the values printed, i.e. not print the shortened rounded value

**Comment by thjsal** [comment]
Looks like the reason is this line: https://github.com/xpsi-group/xpsi/blob/376113f7d63e0aca2bcfc5d7e4f3c3109b6d1eda/xpsi/Likelihood.py#L510

Apparently, there was a bug in this in the Python2 version which @dhuppenkothen fixed. Fixing the bug in importing the native allclose() function of numpy means that the native function can be now used, and apparently, there are no likelihoods printed out from that native function.

**Comment by thjsal** [comment]
In case we want those printings, we should perhaps add such there, or switch back to using the "fallback implementation" of allclose?

**Comment by thjsal** [comment]
Fixed here #235.
