### ISSUE TITLE
Instrument class

### ISSUE THREAD

**Issue by yveskini** [xpsi-group/xpsi#490]
The from_ogip_fits method in Instrument returns channels+1, which means the last channel is included. For consistency with the previous way of doing things, we should be returning channels ( hence last channel is not)

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the from_ogip_fits method to exclude the last channel for consistency with the previous implementation. This ensures that the method returns channels instead of channels+1.

You can review changes in this commit: https://github.com/mnmnk43434/xpsi-group-xpsi-490/commit/2d853849f9f6518eade17e740117c523d6b175bd.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by lmauviard** [comment]
Yes I changed that because I dislike the idea that the input minimum channel is included but not the input maximum channel. I think it is quite misleading...

But if most think that this should be reverted I can do it !

**Comment by drannawatts** [comment]
After lengthy discussion and a bit of voting, we have decided not to do this.
